version: '3.8'

services:
  app:
    build: ""
    ports:
      - 18080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/paneldb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
    networks:
      - sv

  db:
    image: mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin status -U sv"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - ./_db:/var/lib/mysql
    networks:
      - sv

networks:
  sv:
